package com.japanese.reader.service.impl;

import com.japanese.reader.dto.Article;
import com.japanese.reader.dto.Question;
import com.japanese.reader.dto.Sentence;
import com.japanese.reader.exception.BusinessException;
import com.japanese.reader.repository.ArticleRepository;
import com.japanese.reader.repository.QuestionRepository;
import com.japanese.reader.service.AdminService;
import com.japanese.reader.service.SentenceGenerator;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class AdminServiceImpl implements AdminService {

    private final QuestionRepository questionRepository;
    private final ArticleRepository articleRepository;
    private final SentenceGenerator sentenceGenerator;

    private String now() {
        return LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME) + "Z";
    }

    // ========== 题库 ==========

    @Override
    public List<Question> getAllQuestions() {
        return questionRepository.findAll();
    }

    @Override
    public Question createQuestion(Question question) {
        question.setCreatedAt(now());
        question.setUpdatedAt(now());
        if (question.getOptions() != null) {
            question.getOptions().forEach(opt -> opt.setQuestion(question));
        }
        return questionRepository.save(question);
    }

    @Override
    public Question updateQuestion(Long id, Question question) {
        Question existing = questionRepository.findById(id)
                .orElseThrow(() -> new BusinessException(404, "题目不存在，id=" + id));
        question.setId(existing.getId());
        question.setCreatedAt(existing.getCreatedAt());
        question.setUpdatedAt(now());
        if (question.getOptions() != null) {
            question.getOptions().forEach(opt -> opt.setQuestion(question));
        }
        return questionRepository.save(question);
    }

    @Override
    public void deleteQuestion(Long id) {
        if (!questionRepository.existsById(id)) {
            throw new BusinessException(404, "题目不存在，id=" + id);
        }
        questionRepository.deleteById(id);
    }

    @Override
    public int importQuestions(List<Question> questions) {
        questions.forEach(q -> {
            q.setCreatedAt(now());
            q.setUpdatedAt(now());
            if (q.getOptions() != null) {
                q.getOptions().forEach(opt -> opt.setQuestion(q));
            }
        });
        questionRepository.saveAll(questions);
        return questions.size();
    }

    // ========== 文章 ==========

    @Override
    public List<Article> getAllArticles() {
        return articleRepository.findAll();
    }

    @Override
    public Article createArticle(Article article) {
        if (article.getId() == null || article.getId().isBlank()) {
            article.setId(UUID.randomUUID().toString());
        }
        article.setCreatedAt(now());
        article.setUpdatedAt(now());
        if (article.getSentences() == null || article.getSentences().isEmpty()) {
            // 纯文本录入：自动切句并生成假名注音
            article.setSentences(sentenceGenerator.generate(article));
        } else {
            linkSentences(article);
        }
        return articleRepository.save(article);
    }

    @Override
    public Article updateArticle(String id, Article article) {
        Article existing = articleRepository.findById(id)
                .orElseThrow(() -> new BusinessException(404, "文章不存在，id=" + id));
        // 在托管实体上更新字段，避免用 sentences 为 null 的新实例覆盖
        // orphanRemoval 集合（会抛 all-delete-orphan 异常）
        existing.setTitle(article.getTitle());
        existing.setContent(article.getContent());
        existing.setTranslation(article.getTranslation());
        existing.setAudioUrl(article.getAudioUrl());
        existing.setUpdatedAt(now());
        if (existing.getSentences() == null) {
            existing.setSentences(new java.util.ArrayList<>());
        }
        if (article.getSentences() != null && !article.getSentences().isEmpty()) {
            existing.getSentences().clear();
            int i = 0;
            for (Sentence sentence : article.getSentences()) {
                if (sentence.getId() == null || sentence.getId().isBlank()) {
                    sentence.setId(existing.getId() + "-" + (i++));
                }
                sentence.setArticle(existing);
                existing.getSentences().add(sentence);
            }
        } else if (sentenceGenerator.isAutoGenerated(existing.getSentences())) {
            // 纯文本文章（无人工时间轴）：正文/翻译变了就按新文本重建句子和注音；
            // 有人工时间轴的文章只更新正文字段，句子保持不动
            existing.getSentences().clear();
            existing.getSentences().addAll(sentenceGenerator.generate(existing));
        }
        return articleRepository.save(existing);
    }

    private void linkSentences(Article article) {
        if (article.getSentences() == null) {
            return;
        }
        int i = 0;
        for (Sentence sentence : article.getSentences()) {
            if (sentence.getId() == null || sentence.getId().isBlank()) {
                sentence.setId(article.getId() + "-" + (i++));
            }
            sentence.setArticle(article);
        }
    }

    @Override
    public void deleteArticle(String id) {
        if (!articleRepository.existsById(id)) {
            throw new BusinessException(404, "文章不存在，id=" + id);
        }
        articleRepository.deleteById(id);
    }
}
