package com.japanese.reader.service;

import com.atilika.kuromoji.ipadic.Token;
import com.atilika.kuromoji.ipadic.Tokenizer;
import com.japanese.reader.dto.Article;
import com.japanese.reader.dto.RubyWord;
import com.japanese.reader.dto.Sentence;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * 后台纯文本录入的文章没有逐句数据，这里按行切句、按行配对中文翻译，
 * 并用 kuromoji 形态素分析自动生成假名注音。
 * 自动生成的句子没有音频时间轴（startTime/endTime = -1），不参与播放高亮。
 */
@Component
public class SentenceGenerator {

    private final Tokenizer tokenizer = new Tokenizer();

    public List<Sentence> generate(Article article) {
        String content = article.getContent() == null ? "" : article.getContent();
        String translation = article.getTranslation() == null ? "" : article.getTranslation();
        String[] jaLines = content.split("\n");
        String[] zhLines = translation.split("\n");

        // 每次重新生成都用新的 id 前缀，避免与被 orphanRemoval 删除的旧句子撞 id
        String prefix = article.getId() + "-" + UUID.randomUUID().toString().substring(0, 8);

        List<Sentence> sentences = new ArrayList<>();
        int idx = 0;
        for (int i = 0; i < jaLines.length; i++) {
            if (jaLines[i].trim().isEmpty()) continue;
            // 行内再按句号切分，中文同样切分后逐句配对
            List<String> jaSubs = splitBySentenceEnd(jaLines[i].trim());
            List<String> zhSubs = i < zhLines.length ? splitBySentenceEnd(zhLines[i].trim()) : List.of();
            for (int j = 0; j < jaSubs.size(); j++) {
                String zh;
                if (j < jaSubs.size() - 1 || zhSubs.size() <= jaSubs.size()) {
                    zh = j < zhSubs.size() ? zhSubs.get(j) : "";
                } else {
                    // 中文句数多于日文时，多出的部分并入最后一句
                    zh = String.join("", zhSubs.subList(j, zhSubs.size()));
                }
                Sentence sentence = Sentence.builder()
                        .id(prefix + "-" + idx++)
                        .text(jaSubs.get(j))
                        .translation(zh)
                        .startTime(-1)
                        .endTime(-1)
                        .rubyWords(buildRubyWords(jaSubs.get(j)))
                        .build();
                sentence.setArticle(article);
                sentences.add(sentence);
            }
        }
        return sentences;
    }

    /** 按句末标点（。！？!?）切句，标点保留在句尾 */
    private List<String> splitBySentenceEnd(String line) {
        List<String> result = new ArrayList<>();
        StringBuilder current = new StringBuilder();
        for (char c : line.toCharArray()) {
            current.append(c);
            if (c == '。' || c == '！' || c == '？' || c == '!' || c == '?') {
                String s = current.toString().trim();
                if (!s.isEmpty()) result.add(s);
                current.setLength(0);
            }
        }
        String rest = current.toString().trim();
        if (!rest.isEmpty()) result.add(rest);
        return result;
    }

    /** 判断已有句子是否为自动生成（无时间轴），编辑正文后可安全重建 */
    public boolean isAutoGenerated(List<Sentence> sentences) {
        return sentences == null || sentences.isEmpty()
                || sentences.stream().allMatch(s -> s.getStartTime() < 0);
    }

    private List<RubyWord> buildRubyWords(String text) {
        List<RubyWord> words = new ArrayList<>();
        StringBuilder plain = new StringBuilder();
        for (Token token : tokenizer.tokenize(text)) {
            String surface = token.getSurface();
            String reading = token.getReading();
            if (!containsKanji(surface) || reading == null || "*".equals(reading)) {
                plain.append(surface);
                continue;
            }
            String hira = kataToHira(reading);
            // 去掉表面形与读音相同的送り仮名前后缀，让注音只覆盖汉字部分
            // 例：助かる(たすかる) -> 助=たす + かる
            int prefixLen = 0;
            while (prefixLen < surface.length() && prefixLen < hira.length()
                    && !isKanji(surface.charAt(prefixLen))
                    && kataToHira(String.valueOf(surface.charAt(prefixLen))).charAt(0) == hira.charAt(prefixLen)) {
                prefixLen++;
            }
            int suffixLen = 0;
            while (suffixLen < surface.length() - prefixLen && suffixLen < hira.length() - prefixLen
                    && !isKanji(surface.charAt(surface.length() - 1 - suffixLen))
                    && kataToHira(String.valueOf(surface.charAt(surface.length() - 1 - suffixLen))).charAt(0)
                            == hira.charAt(hira.length() - 1 - suffixLen)) {
                suffixLen++;
            }
            String core = surface.substring(prefixLen, surface.length() - suffixLen);
            String coreRuby = hira.substring(prefixLen, hira.length() - suffixLen);
            plain.append(surface, 0, prefixLen);
            flushPlain(words, plain);
            words.add(new RubyWord(core, coreRuby));
            plain.append(surface, surface.length() - suffixLen, surface.length());
        }
        flushPlain(words, plain);
        return words;
    }

    private void flushPlain(List<RubyWord> words, StringBuilder plain) {
        if (plain.length() > 0) {
            words.add(new RubyWord(plain.toString(), null));
            plain.setLength(0);
        }
    }

    private boolean containsKanji(String s) {
        for (char c : s.toCharArray()) {
            if (isKanji(c)) return true;
        }
        return false;
    }

    private boolean isKanji(char c) {
        return (c >= 0x4E00 && c <= 0x9FFF) || c == '々' || c == '〆' || c == 'ヶ';
    }

    private String kataToHira(String kata) {
        StringBuilder sb = new StringBuilder(kata.length());
        for (char c : kata.toCharArray()) {
            sb.append(c >= 'ァ' && c <= 'ヶ' ? (char) (c - 0x60) : c);
        }
        return sb.toString();
    }
}
